apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api-deployment
spec:
  selector:
    matchLabels:
      app: dotnet
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: blazor
        image: guillaumeutopios/apiweatherforecast:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-blazor-deployment
spec:
  selector:
    matchLabels:
      app: dotnet
  replicas: 2
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: api
        image: guillaumeutopios/blazorweatherforecast:latest
        ports:
        - containerPort: 80
